version: "3.7"

services:

  debezium:
    build:
      context: debezium-server
      dockerfile: Dockerfile
    container_name: dbz-server
    depends_on:
      - sink
      - source
    environment:
      # input (database to follow events from)
      # https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-connector-properties
      - DEBEZIUM_SOURCE_CONNECTOR_CLASS=io.debezium.connector.postgresql.PostgresConnector
      - DEBEZIUM_SOURCE_DATABASE_USER=user
      - DEBEZIUM_SOURCE_DATABASE_PASSWORD=S3cr3T
      - DEBEZIUM_SOURCE_DATABASE_HOSTNAME=source
      - DEBEZIUM_SOURCE_DATABASE_PORT=5432
      - DEBEZIUM_SOURCE_DATABASE_DBNAME=data
      - DEBEZIUM_SOURCE_DATABASE_SERVER_NAME=data
      - DEBEZIUM_SOURCE_OFFSET_FLUSH_INTERVAL_MS=0
      - DEBEZIUM_SOURCE_OFFSET_STORAGE_FILE_FILENAME=data/offsets.dat
      - DEBEZIUM_SOURCE_PLUGIN_NAME=pgoutput
      - DEBEZIUM_SOURCE_TOMBSTONES_ON_DELETE=false
      # output (queue and/or store for generated events)
      # https://debezium.io/documentation/reference/stable/operations/debezium-server.html#_redis_stream
      - DEBEZIUM_SINK_TYPE=redis
      - DEBEZIUM_SINK_REDIS_ADDRESS=sink:6379
      - DEBEZIUM_SINK_REDIS_PASSWORD=S3cr3T
      - DEBEZIUM_SINK_REDIS_NULL_KEY=NullPrimaryKey
    image: dbz-server
    networks:
      - dbznet
    ports:
      - 8080:8080
    restart: unless-stopped

  source:
    build:
      context: debezium-source
      dockerfile: Dockerfile
    container_name: dbz-pgsql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=S3cr3T
      - POSTGRES_DB=data
    image: dbz-pgsql
    networks:
      - dbznet
    ports:
      - 5432:5432
    restart: unless-stopped

  sink:
    build:
      context: debezium-sink
      dockerfile: Dockerfile
    container_name: dbz-redis
    image: dbz-redis
    networks:
      - dbznet
    ports:
      - 6379:6379
    restart: unless-stopped

  producer:
    build:
      context: producer
      dockerfile: Dockerfile
    container_name: dbz-prod
    depends_on:
      - source
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=S3cr3T
      - POSTGRES_HOST=source
      - POSTGRES_PORT=5432
      - POSTGRES_DB=data
    image: dbz-prod
    networks:
      - dbznet
    restart: unless-stopped

  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile
    container_name: dbz-cons
    depends_on:
      - sink
    environment:
      - REDIS_PASSWORD=S3cr3T
      - REDIS_HOST=sink
      - REDIS_PORT=6379
      - REDIS_DB=0
    image: dbz-cons
    networks:
      - dbznet
    restart: unless-stopped

networks:
  dbznet:
    name: dbznet
